name: Start New Game

on:
  create:

jobs:
  init-game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set Up Game State
        run: |
          cp ./states/game-state-template.json ./states/game-state-${{ github.ref_name }}.json

      - name: Commit Initial Game State
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./states/game-state-${{ github.ref_name }}.json
          git commit -m "Initialize a new game"
          git push --set-upstream origin ${{ github.ref_name }}

      - name: Create Pull Request
        id: create_pr
        run: |
          gh pr create --base main \
            --head ${{ github.ref_name }} \
            --title "NEW GAME STARTED!" \
            --body "🎮 **LET THE GAMES BEGIN!** 🎮\
              Get ready to play and have fun! 🚀\
              Player 2 will start the game. 🎲\
              "
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
          echo "PR_NUMBER=$(echo $PR_URL | grep -oE '[0-9]+$')" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Markdown Summary
        id: generate_game_state_markdown
        uses: Ma11hewThomas/github-markdown-builder@v1
        with:
          template-file-path: "./states/game-state.hbs"
          json-file-path: "./states/game-state-${{ github.ref_name }}.json"
          summary: true
          pull-request: true

      - name: Comment PR with Game State
        uses: thollander/actions-comment-pull-request@v3
        with:
          pr-number: ${{ steps.create_pr.outputs.PR_NUMBER }}
          message: ${{ github.ref_name }}