name: Clean Up Game State

on:
  pull_request:
    types: [closed]
  delete:

jobs:
  cleanup-game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract branch name
        id: extract_branch_name
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BRANCH_NAME=$(gh pr view ${{ github.event.number }} --json headRefName -q '.headRefName')
          else
            BRANCH_NAME=${{ github.ref_name }}
          fi
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
        
      - name: Remove Game State File
        run: |
          rm -f ./game-state-${{ steps.extract_branch_name.outputs.branch_name }}.json

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -u
          git commit -m "Clean up game state"
          git push
  