name: Process Game Logic

on:
  issue_comment:
    types: [created]

jobs:
  process_comment:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Display Event Payload
        run: |
          echo "Event Payload:"
          echo "${{ toJson(github.event) }}"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Branch Name from PR ID
        id: extract_branch
        run: |
          pr_number=${{ github.event.issue.number }}
          BRANCH_NAME=$(gh pr view $pr_number --json headRefName -q '.headRefName')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "Branch name extracted from PR: $BRANCH_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.extract_branch.outputs.BRANCH_NAME }}

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      #      - name: Install Dependencies
      #        run: |
      #          python -m pip install --upgrade pip
      #          pip install -r requirements.txt

      - name: Process Comment Commands
        if: ${{ github.event.comment.body }}
        run: |
          COMMENT="${{ github.event.comment.body }}"
          if [[ $COMMENT =~ ^move\ ([0-9]+)\ ([0-9]+)$ ]]; then
            ROW=${BASH_REMATCH[1]}
            COL=${BASH_REMATCH[2]}
            echo "Moving to row $ROW, col $COL"
            # python bubble_pop_game.py move $ROW $COL
            # mv game_state.json ./states/game-state-${{ steps.extract_branch.outputs.BRANCH_NAME }}.json
          else
            echo "Invalid command. Use 'move <row> <col>' to pop a bubble."
          fi

      #      - name: Commit Game State
      #        run: |
      #          git config --global user.name "github-actions[bot]"
      #          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #          git add ./states/game-state-${{ steps.extract_branch.outputs.BRANCH_NAME }}.json
      #          git commit -m "Update game state"
      #          git push

      - name: Generate Markdown Summary
        id: generate_game_state_markdown
        uses: Ma11hewThomas/github-markdown-builder@v1
        with:
          template-file-path: "./states/game-state.hbs"
          json-file-path: "./states/game-state-${{ steps.extract_branch.outputs.BRANCH_NAME }}.json"
          summary: true
          pull-request: true

      - name: Comment PR with Game State
        uses: thollander/actions-comment-pull-request@v3
        with:
          pr-number: ${{ github.event.pull_request.number }}
          message: ${{ steps.generate_game_state_markdown.outputs.markdown }}
