name: Process Game Logic

on:
  issue_comment:
    types: [created]

jobs:
  process_comment:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Display Event Payload
        run: |
          echo "Event Payload:"
          echo "${{ toJson(github.event) }}"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Branch Name from PR ID
        id: extract_branch
        run: |
          pr_number=${{ github.event.issue.number }}
          BRANCH_NAME=$(gh pr view $pr_number --json headRefName -q '.headRefName')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "Branch name extracted from PR: $BRANCH_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.extract_branch.outputs.BRANCH_NAME }}

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      #      - name: Install Dependencies
      #        run: |
      #          python -m pip install --upgrade pip
      #          pip install -r requirements.txt

      - name: Process Comment for Move Command
        if: ${{ github.event.comment.body }}
        run: |
          echo "Processing comment: ${{ github.event.comment.body }}"
          COMMENT="${{ github.event.comment.body }}"
          echo "Comment: $COMMENT"
          if [[ "$COMMENT" =~ ^move\ ([A-Za-z])\ ([0-9]+)$ ]]; then
            # Extract row letter and column number from the comment
            ROW_LETTER=${BASH_REMATCH[1]}
            COL=${BASH_REMATCH[2]}

            # Convert the row letter (A-Z or a-z) to a zero-based index
            ROW=$(printf "%d" "'${ROW_LETTER^^}")   # Convert to uppercase
            ROW=$((ROW - 65))                       # 'A' (ASCII 65) becomes 0

            echo "Moving to row $ROW (original: $ROW_LETTER), col $COL"

            mv ./states/game-state-${{ steps.extract_branch.outputs.BRANCH_NAME }}.json game_state.json

            # Debug current directory
            echo "Current directory: $(pwd)"

            # Run Python game logic script
            python bubble_pop_game.py move $ROW $COL || echo "Python script error" >> error.log
            if [ -f error.log ]; then
              echo "Error occurred during Python script execution"
              exit 1
            else
              mv game_state.json ./states/game-state-${{ steps.extract_branch.outputs.BRANCH_NAME }}.json
            fi
          fi

      - name: Comment on PR with Error
        if: failure()
        uses: thollander/actions-comment-pull-request@v3
        with:
          pr-number: ${{ github.event.pull_request.number }}
          message: "An error occurred while processing the move command. Please check the workflow logs for details."

      - name: Commit Game State
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./states/game-state-${{ steps.extract_branch.outputs.BRANCH_NAME }}.json
          git commit -m "Update game state"
          git push --set-upstream origin ${{ steps.extract_branch.outputs.BRANCH_NAME }}

      - name: Generate Markdown Game State
        if: success()
        id: generate_game_state_markdown
        uses: Ma11hewThomas/github-markdown-builder@v1
        with:
          template-file-path: "./states/game-state.hbs"
          json-file-path: "./states/game-state-${{ steps.extract_branch.outputs.BRANCH_NAME }}.json"
          summary: true

      - name: Comment PR with Game State
        if: success()
        uses: thollander/actions-comment-pull-request@v3
        with:
          pr-number: ${{ github.event.pull_request.number }}
          message: ${{ steps.generate_game_state_markdown.outputs.markdown }}
