name: Clean Up Game State

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract branch name
        id: extract_branch_name
        run: |
          BRANCH_NAME=$(gh pr view ${{ github.event.number }} --json headRefName -q '.headRefName')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove Branch
        run: |
          git push origin --delete ${{ steps.extract_branch_name.outputs.BRANCH_NAME }}
          gh pr close ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
