name: Initialize Game State

on:
  pull_request:
    types: [opened]
  create:
    branches:
      - '*'
      - '!main'

jobs:
  init-game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Game State
        run: |
          branch_name=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          cp game-state-template.json game-state-${branch_name}.json

      - name: Commit Game State
        run: |
          branch_name=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add game-state-${branch_name}.json
          git commit -m "Initialize game state for ${branch_name}"
          git push
