name: Start New Game

on:
  create:

jobs:
  init-game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set Up Game State
        run: |
          cp ./states/game-state-template.json ./states/game-state-${{ github.ref_name }}.json

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: NEW GAME STARTED!
          base: main
          branch: ${{ github.ref_name }}
          add-paths: |
            ./states/game-state-${{ github.ref_name }}.json
          draft: true
          title: NEW GAME STARTED!
          body: |
            🎮 **LET THE GAMES BEGIN!** 🎮
            Get ready to play and have fun! 🚀

            Player 2 will start the game. 🎲
